// Tensor Streaming Protocol
//
// This protocol defines a streaming mechanism used for communication between a host and a board.
// One board may have one or more devices, and each device can have multiple input/output data streams.
// For example:
// - Sensors typically have one output stream.
// - Models have at least one input and one output stream.
// - Playback devices may only have an input stream.
//
//
// Example:
//
// [<= BoardCapabilitiesRequest]
//   The host sends a BoardCapabilitiesRequest message to inquire about the device capabilities.
//
// [=> BoardCapabilitiesResponse]
//   The device responds with a BoardCapabilitiesResponse message detailing the available devices.
//   If BoardCapabilitiesResponse.watchdog_timeout is defined (>0), the host must send a WatchdogResetRequest
//   at specified intervals (in milliseconds) to prevent the device from resetting itself.
//
// [<= WatchdogResetRequest]
//   Resets the watchdog timer on the device. This request should be sent repeatedly every watchdog_timeout milliseconds.
//
// For each device of interest:
//
// [<= DeviceConfigurationRequest]
//   Configures the specified device. This request may not initialize the device but will prompt a response
//   with a DeviceConfigurationResponse message that defines the expected data when a subscription is started.
//
// [=> DeviceConfigurationResponse]
//   Describes the data streams (input/output) of the device once a subscription is started.
//
// [<= SubscribeRequest]
//   Initiates data streaming for the specified device. This request may also initialize the device if the firmware
//   has not done so already.
//
// [=> DataChunk]
//   For each subscription, the device streams data in DataChunk messages.

// General Notes:
//   - Avoid using '\r' in strings

syntax = "proto3";

import "model.proto";

package protocol;

// Wrapper message for all request types.
message Request {
    oneof request_type {
        BoardCapabilitiesRequest capabilities = 1;  
		DeviceConfigurationRequest config = 2;
		StartRequest start = 3;
		StopRequest stop = 4;
        WatchdogResetRequest watchdog_reset = 5;
        DataChunk data = 6;
    }
}

// Wrapper message for all response types.
message Response {
    oneof response_type {
        BoardCapabilitiesResponse capabilities = 1;
		DeviceConfigurationResponse config = 2;
        ErrorResponse error = 3; 
        DataChunk data = 4; 
    }
}

// Message to request the capabilities of the board. A board contains one or more devices.
message BoardCapabilitiesRequest {
    // If negative all devices are in response.
    int32 device = 1; 
}

// Message representing the capabilities of the board.
message BoardCapabilitiesResponse {
	Board board = 1;
}

// Represents an option value for device configuration.
message OptionValue {
    int32 option_id = 1;

    oneof value {
        int32 int_value = 2;    // Integer value
        float float_value = 3;  // Floating-point value
        bool bool_value = 4;    // Boolean value
        int32 oneof_value = 5;  // Index into OptionOneOf items
    }
}

// Request to configure a device. This may not necessarily initialize the device
// but will reply with a DeviceConfigurationResponse that defines the data to expect once a subscription is started.
message DeviceConfigurationRequest {
    // The device to configure (index)
    int32 device = 1;
	
    // The option values for configuration
    repeated OptionValue options = 2; 
}

// Response message describing the device configuration.
message DeviceConfigurationResponse {
     // The device that was configured
	int32 device = 1;

    // All the option values
    repeated OptionValue options = 2;

    // Device streams
    repeated StreamConfig streams = 3;

    // The status of the device 
    DeviceStatus status = 4;

    // Optional status message
    string status_message = 5;
}

// Message to start streaming data for a specified device.
message StartRequest {
    // The device index to start streaming.
    int32 device = 1;
}

// Message to stop streaming data for a specified device.
message StopRequest {
    // The device index to stop streaming. If negative, all streaming is stopped.
    int32 device = 1;
}

// Represents a chunk of data streamed from a device.
message DataChunk {
	// The device index this data originates from.
	int32 device = 1;

    // Device stream index 
    int32 stream = 2;
	
	// The number of frames. This value is equal to or less than StreamConfiguration.max_frame_count
	int32 frame_count = 3;

	// The size of the payload in bytes is: sizeof(DataType) * shape.flat * frame_count
	bytes payload = 4;
}

/******************************* ErrorResponse and WatchdogResetRequest *******************************/

// Message representing an error response.
message ErrorResponse {
    string error_message = 1;   // Description of the error
    int32 error_code = 2;       // Error code
}

// Request to reset the watchdog timer on the device. This prevents the device from resetting itself.
message WatchdogResetRequest {}


