/******************************************************************************
* File Name:   dummy_driver.h
*
* Description: This file generates cyclical data to mock data that could have 
* been generated by a sensor.
*              
*******************************************************************************/

#ifndef __DUMMY_DRIVER_H_
#define __DUMMY_DRIVER_H_

#include <stdio.h>
#include <stdlib.h>
#include <inttypes.h>
#include <stdbool.h>

#include "clock.h"

bool fetch_dummy_driver_data( int waveform, int scaling, bool apply, int16_t* buffer );
bool reset_dummy_driver(void);

#endif


