/******************************************************************************
* File Name:   dummy_driver.c
*
* Description: This file generates cyclical data to mock data that could have 
* been generated by a sensor.
*
*******************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <inttypes.h>
#include <stdbool.h>

#include "clock.h"

/******************************************************************************
 * Macros
 *****************************************************************************/

/******************************************************************************
 * Global Variables
 *****************************************************************************/
// Have a clock here to ensure we are sending the data at the correct rate. 
static clock_tick_t next_action_time = 0;

int16_t mockup_data[4][80] =    { // Sawtooth
                                    { 0,1,2,3,4,5,6,7,8,9,
                                      10,11,12,13,14,15,16,17,18,19,
                                      20,21,22,23,24,25,26,27,28,29,
                                      30,31,32,33,34,35,36,37,38,39,
                                      40,41,42,43,44,45,46,47,48,49,
                                      50,51,52,53,54,55,56,57,58,59,
                                      60,61,62,63,64,65,66,67,68,69,
                                      70,71,72,73,74,75,76,77,78,79 },
                                    // Triangle
                                    { 0,1,2,3,4,5,6,7,8,9,
                                      10,11,12,13,14,15,16,17,18,19,
                                      20,21,22,23,24,25,26,27,28,29,
                                      30,31,32,33,34,35,36,37,38,39,
                                      40,39,38,37,36,35,34,33,32,31,
                                      30,29,28,27,26,27,24,23,22,21,
                                      20,19,18,17,16,15,14,13,12,11,
                                      10,9,8,7,6,5,4,3,2,1 },
                                    
                                    // Square
                                    { 0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,
                                      40,40,40,40,40,40,40,40,40,40,
                                      40,40,40,40,40,40,40,40,40,40,
                                      40,40,40,40,40,40,40,40,40,40,
                                      40,40,40,40,40,40,40,40,40,40,
                                      0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0 },
                                    
                                    // Sinus
                                    { 0,2,4,6,8,10,11,13,15,16,
                                      18,19,20,21,22,23,24,24,25,25,
                                      25,25,25,24,24,23,22,21,20,19,
                                      18,16,15,13,11,10,8,6,4,2,
                                      0,-2,-4,-6,-8,-10,-11,-13,-15,-16,
                                      -18,-19,-20,-21,-22,-23,-24,-24,-25,-25,
                                      -25,-25,-25,-24,-24,-23,-22,-21,-20,-19,
                                      -18,-16,-15,-13,-11,-10,-8,-6,-4,-2 }
                                };

/*******************************************************************************
* Function Prototypes
*******************************************************************************/

/*******************************************************************************
* Function Definitions
*******************************************************************************/

/******************************************************************************
* Function Name: fetch_driver_data
********************************************************************************
* Summary:
*   Fetch data from a driver mockup into the buffer.
*   This is just an example and is moved out to keep the protocol part 
*   clean.
*
* Parameters:
*   waveform:   In this example case a value from 0-3.
*   scaling:    Value that we get from the protocol option.
*   apply:      Boolean that lets us know if scaling should be applied.
*   buffer:     Where to copy any device data to before transportation 
*               over the protocol.
*
* Return:
*   True if there was data to fetch. False if no data should be sent.
*
* Note: -->>>>>> THIS IS ONLY A MOCKUP! <<<<<<--
*       This is only a mock-up and only sends static data from a table.
*       This should be replaced! Any method of collecting data can 
*       be used. The code can also be put in the polling function itself.
*       It can be very different.
*
*******************************************************************************/

bool fetch_dummy_driver_data( int waveform, int scaling, bool apply, int16_t* buffer ){
    /* This is a simple driver that copies data from a static array
    ** into the destination buffer for sending it out to studio.
    ** Waveform is an index into the static data table where each block
    ** holds 80 samples.
    
    NOTE: These data packets comes from configure_streams..
    
    
    
    ** Buffer is a destination where the data should be put. Possible
    ** after scaling.
    ** We provide the flags from the settings through individual arguments.
    ** Another option is to send the driver struct holding the needed states.
    */

#define DELTA_TIME ( CLOCK_TICK_PER_SECOND / 100 )
    // If recently started or reset.
    if (next_action_time == 0) {
        next_action_time = clock_get_tick();
    }

    clock_tick_t current_time = clock_get_tick();

    // We are expecting this to generate valid data 100 times a second.
    if (current_time > next_action_time) {
        
        // Add to the clock the expected timing of the next event.
        next_action_time += DELTA_TIME;
        
        // Override the scaling if it shouldn't be applied.
        if ( apply == false ){
            scaling=1;
        }
        
        // Copy and scale dummy data.
        for ( int x=0; x<80; x++ ){
            *buffer = mockup_data[waveform][x] * scaling;
            buffer++;
        }

        // Data is ready for sending.
        return true;

    }
    
    // No data this polling round.
    return false;
 
}

bool reset_dummy_driver(void){
    next_action_time = 0;
    return true;
}

